schema="""
-- MySQL Script generated by MySQL Workbench
-- Wed Jul  9 21:22:00 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_projeto` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `db_projeto` ;

-- -----------------------------------------------------
-- Table `db_projeto`.`alembic_version`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`alembic_version` (
  `version_num` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`version_num`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(128) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `senha` VARCHAR(128) NOT NULL,
  `telefone` VARCHAR(11) NULL DEFAULT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`cliente` (
  `id` INT NOT NULL,
  `cpf` VARCHAR(11) NOT NULL,
  `data_nascimento` VARCHAR(10) NULL DEFAULT NULL,
  `endereco` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf` (`cpf` ASC) VISIBLE,
  CONSTRAINT `cliente_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `db_projeto`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(14) NOT NULL,
  `razao_social` VARCHAR(128) NOT NULL,
  `nome_fantasia` VARCHAR(128) NULL DEFAULT NULL,
  `numero_contato` VARCHAR(11) NULL DEFAULT NULL,
  `email_contato` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`livro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(256) NOT NULL,
  `autor` VARCHAR(128) NOT NULL,
  `editora` VARCHAR(128) NOT NULL,
  `isbn` VARCHAR(13) NOT NULL,
  `ano_publicacao` INT NOT NULL,
  `edicao` VARCHAR(32) NULL DEFAULT NULL,
  `categoria` VARCHAR(64) NOT NULL,
  `quantidade_total` INT NOT NULL,
  `quantidade_disponivel` INT NOT NULL,
  `localizacao` VARCHAR(32) NOT NULL,
  `descricao` VARCHAR(512) NULL DEFAULT NULL,
  `preco_compra` FLOAT NULL DEFAULT NULL,
  `data_aquisicao` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  `observacoes` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`emprestimo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cliente_id` INT NOT NULL,
  `livro_id` INT NOT NULL,
  `data_emprestimo` DATETIME NOT NULL,
  `data_devolucao_prevista` DATETIME NOT NULL,
  `data_devolucao_real` DATETIME NULL DEFAULT NULL,
  `status` VARCHAR(20) NOT NULL,
  `multa` FLOAT NULL DEFAULT NULL,
  `observacoes` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cliente_id` (`cliente_id` ASC) VISIBLE,
  INDEX `livro_id` (`livro_id` ASC) VISIBLE,
  CONSTRAINT `emprestimo_ibfk_1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `db_projeto`.`cliente` (`id`),
  CONSTRAINT `emprestimo_ibfk_2`
    FOREIGN KEY (`livro_id`)
    REFERENCES `db_projeto`.`livro` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `db_projeto`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_projeto`.`funcionario` (
  `id` INT NOT NULL,
  `cargo` VARCHAR(64) NOT NULL,
  `departamento` VARCHAR(64) NULL DEFAULT NULL,
  `data_contratacao` VARCHAR(10) NOT NULL,
  `salario` FLOAT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `funcionario_ibfk_1`
    FOREIGN KEY (`id`)
    REFERENCES `db_projeto`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

"""